### ISSUE TITLE
[Android Auto] Not cached songs issue

### ISSUE THREAD

**Issue by LEOSCHUMY** [knighthat/Kreate#370]
### Version of Kreate

v.1.4.1-m

### Android version

15 [VANILLA_ICE_CREAM]

### TODOs before submitting a ticket

- [x] Update my app to latest version (see link below)
- [x] (If I'm on latest version) Re-install app
- [x] I have checked issue page and there's no problem like mine

### Tell us how to trigger this bug

1. Connect your smartphone to the car’s infotainment system using a USB cable.
2. From the car’s display, launch the Kreate app.
3. Navigate to an artist or album where you have never played any tracks before.
4. Select a track you’ve never played.
5. Wait for the car display to show: **“source error”. Playback will not start**.
6. Now, keeping the phone still connected via USB, switch to your smartphone.
7. Open the Kreate app directly on your phone.
8. From the car’s display, select the exact same track again.
9. Observe that the track now plays successfully.

### Submit a video

Since Android 12, a screen recorder is baked into the OS, for your convenience! Older versions require additional software to do so.

> Here's an [instruction video](https://www.youtube.com/watch?v=h6fOErvWIGI)

### What was your expectation?

Playback should work even if the app is not launched from the smartphone

### Logs (Optional)

(https://pastebin.com/5zsRJYfq)

**Comment by knighthat** [comment]
did it work with cached or downloaded songs?

**Comment by LEOSCHUMY** [comment]
Yes, no problems with cached or downloaded songs

**Comment by knighthat** [comment]
does your phone have a feature where it blocks internet access from a specific app? 

Looks like for whatever reason, Android Auto tried to use internet and it failed. I'm not 100% sure on the audio part, but the process of getting song's thumbnail failed, as shown in your crash log

```
2025-06-07 09:06:15:715 ERROR: RealImageLoader - Failed to load bitmap java.lang.IllegalStateException: Unable to create a fetcher that supports: null
	at coil.intercept.EngineInterceptor.fetch(SourceFile:243)
	at coil.intercept.EngineInterceptor.access$execute(SourceFile:196)
	at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(SourceFile:41)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:115)
	at androidx.core.app.ActivityRecreator$1.run$kotlinx$coroutines$internal$LimitedDispatcher$Worker(SourceFile:6)
	at androidx.core.app.ActivityRecreator$1.run(SourceFile:99)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
```

**Comment by LEOSCHUMY** [comment]
My rom has a function to block internet access, but I don't use it, and there are no blocks for Android Auto or Kreate.
On Android Auto, I don't have the same issue with other closed apps (for example, Weather or Podcast)

**Comment by knighthat** [comment]
that's weird, now that I read the crash log again, here's the error:

```
2025-06-07 09:06:01:489 ERROR: PlayerServiceModern - PlayerServiceModern onPlayerError error code 2000 message Source error cause 
```

Code `2000` means `ERROR_CODE_IO_UNSPECIFIED`. This include disk read/write operation, as well as network connection.

Based on your previous answer `no problems with cached or downloaded songs`, combine with error with failure in fetching thumbnail. I am almost 100% sure that Android Auto is blocked from accessing the internet (at least when it's going through Kreate)

---

Small note, Kreate doesn't handle network requests when it's connected to Android Auto (at least not entirely).

I'm using GrapheneOS where I can block Android Auto from accessing the internet , this breaks fetching thumbnail, but I can still listen to uncached songs

---

I have a few suggestions:

1. Try other songs, from completely different artists, albums, playlists, etc.
2. Try using different YT music app (could it be your DNS blocks YT's domain names?)
3. Check storage

**Comment by knighthat** [comment]
Or you also can re-install the app (you don't have to uninstall it first, just download [latest version](https://github.com/knighthat/Kreate/releases/tag/v1.4.2) and install on top of current version). 

I have seen people fixing some weird bugs by doing this, so it may worth a try

**Comment by LEOSCHUMY** [comment]
Done (without any good news):
>     1. Try other songs, from completely different artists, albums, playlists, etc.
>     3. Check storage
>      re-install the app


To do (asap)
>      2. Try using different YT music app (could it be your DNS blocks YT's domain names?)

**Comment by adamcarter81** [comment]
I have noticed this issue as well - on Android Auto if I search for a song/artist/album and hit play - I get the source not found error. But on the app on phone it has the search result ready, hitting play on the phone then plays it on AA. I'm using the default YT app, and Kreate works just fine on the phone.
This has happened on the last 3 weekly builds - I don't know before that, as I never used it before then

**Comment by knighthat** [comment]
does the official YTM app work on Android Auto?

**Comment by DjRom64** [comment]
YTM does not work well on Android auto, it's very limited, all I can do is listen to on device songs but no online playlists or search whatsoever. Maybe with premium account it is better...

**Comment by knighthat** [comment]
have you try other front-end alternatives? What I'm trying to gather here is whether you can access YT's CDN. There's a guy got block (idk the root cause) to Google's CDN, he couldn't get song's thumbnail, the problem remains unsolved til' this day

**Comment by DjRom64** [comment]
I can certainly try other front ends if that helps, what do you suggest?

**Comment by knighthat** [comment]
maybe Piped or metrolist, I know some of them do the server-side rendering, so **avoid** those. You need to let your phone make requests

**Comment by DjRom64** [comment]
I tried a coupled of Piped Apps but no result. Metrolist can't even search in AA. That's the point in Kreate the search in AA works and is correct and return the correct set so it is not blocked from YT.

**Comment by DjRom64** [comment]
Newpipe has it working in their latest nighlty.
https://github.com/TeamNewPipe/NewPipe-nightly/releases

**Comment by knighthat** [comment]
what build of Kreate are you using? `minified`, `full`, `fdroid`, or `izzy`?

**Comment by DjRom64** [comment]
minifield

**Comment by knighthat** [comment]
can you switch to `full`? You can install it on top of current build, no data will be lost

**Comment by DjRom64** [comment]
I confirm It works with Full version! It seems that some code is not so useless in there :) 
Problem Solved!

**Comment by knighthat** [comment]
This is exactly why I include `full` build. Glad it solves your problem

**Comment by LEOSCHUMY** [comment]
However full version (v1.5.1-20250622) doesn't solve initial issue

**Comment by knighthat** [comment]
Still getting `Source error` in AA?

**Comment by LEOSCHUMY** [comment]
Yes, same error.
If I start Kreate on my smartphone first and then select a new song on Android Auto, it works.
But if I don't start Kreate beforehand, the new song doesn't play.

**Comment by knighthat** [comment]
Can you try this. Go to player on your phone, hold play button to open `playback parameters`, then slide `medley duration` to 0. After that, try playing a song on AA to see if problem goes away?

**Comment by LEOSCHUMY** [comment]
> Can you try this. Go to player on your phone, hold play button to open `playback parameters`, then slide `medley duration` to 0. After that, try playing a song on AA to see if problem goes away?


Issue persists

**Comment by knighthat** [comment]
:tada: This issue has now been fixed and is available in [v1.6.1](https://github.com/knighthat/Kreate/releases/tag/v1.6.1) :tada:
This ticket is now closed. If you have any more question, feel free to reply below. If needed, the ticket will be re-open for further support.
